### PR TITLE
Webpack for build configurations.

### PR DESCRIPTION
**Pull request by nim23**
I would probably class this as a bit controversial so let's have conversation's over here before merging it. I am completely cool with not merging it as well. TLDR; Provides foundation for being able to modularise the front-end code, which at the moment are bunch of huge files.

Summary for commit:
a. Use's webpack for building js. This should give us more flexibility moving forward, as this opens up the possibility to easily modularise the code on the front end. On the long run this should help to keep the code base maintainable.

b. Template's are now included in the minified file's and no longer require a round trip to the server, as it happen's today. This shaves off somewhat of 0.7 to 1 second of time on a Good 3G connection. Win Win.

c. In addition to being able to modularise the code webpack opens up the possibility to use ES6 for the project should we chose it, plus a whole host of plugin's and ecosystem around webpack becomes accessible.

Warnings:
1. Changes the dev process slightly. Previously we would simply do npm start, make changes to the front-end code and reload the page. Now there's a two step process
   
    i. npm build-dev [build's a bundle.js and start's watching for any changes]
   ii. npm start

After this the process stays the same for any front-end dev.

### CODE REVIEW

**Comment by dawalama** [comment]
The two steps you mentioned can be made into one by wrapping it in a script. 

I vote yes

**Comment by tux4** [comment]
Excellent!

**Comment by nim23** [comment]
@dawalama would be nice to do by wrapping it in a script, can you give me more hint's as to how to do it?

**Comment by dawalama** [comment]
@nim23 
I was simply thinking of putting all the required steps in a bash script 

!#/usr/bin/env sh 
npm build-dev  && npm start

**Comment by shri3k** [comment]
@dawalama that's old school way of doing things man. :smile:  It's all about `npm scripts` these days. What's awesome about them is they're cross platform too. :wink:

**Comment by shri3k** [comment]
@nim23 if we're gonna be using `webpack`then maybe we don't the need to use `gulp` anymore? Kinda feels redundant but I can see some use cases of `gulp` too. I **have** used `browserify` before though so I see why it's controversial. hehe.

**Comment by dawalama** [comment]
Dawa Lama
- Mobile phone brevity in effect

> On May 4, 2015, at 2:30 PM, Yojan Shrestha notifications@github.com wrote:
> 
> @dawalama that's old school way of doing things man. :) It's all about npm scripts these days. What's awesome about them is they're cross platform too. ;)

I just got called out for being old. Old is gold !

**Comment by shri3k** [comment]
@dawalama haha. Not attacking your age at all. `shell scripts` has it's purpose too at times. `npm scripts` just makes sense in this case.

**Comment by shri3k** [comment]
@nim23 I didn't get a chance to read the steps earlier but you can perhaps wrap those two scripts into one by creating a new property on `scripts` with called maybe `npm build-dev-watch` and with the value `npm build-dev && npm start`. That way we can just fire up `npm build-dev-watch` and be done with those two steps.

**Comment by nim23** [comment]
@sinkingshriek let's keep gulp hanging, I have some more ideas about improving the front-end workflow and it's going to be handy doing that. I tried wrapping those two step's into one, but it doesn't work. I will try and see if I can combine those two steps via gulp.

**Comment by nim23** [comment]
never mind `npm run buil-dev & npm start` does the trick. I will update the pull request this evening. Plus need to add few more comments.

**Comment by shri3k** [comment]
@nim23 ah..I had a typo there but glad you picked that up.

**Comment by nim23** [comment]
This diff is now updated to support  `npm run build-dev-watch`, instead of the two step process.

**Comment by shri3k** [comment]
@nim23 One more thing. I don't think it's good to put our db password out in public. Can you reset that change? Other than that I think we're almost ready to merge it with `master`.

**Comment by nim23** [comment]
@sinkingshriek My bad, was playing around and forgot to remove it.

**Comment by nim23** [comment]
@sinkingshriek what is the error that you are getting?

**Comment by shri3k** [comment]
It's probably the major refactor that I'm doing on routes and maybe it's causing the issue. I'll test again tonight and let you know

**Comment by shri3k** [comment]
Looks good. Merging.

**Pull request merged**
